### ISSUE TITLE
Android Build fail: Missing one of the key attributes 'action#name,category#name'

### ISSUE THREAD

**Issue by whyameye** [mobimentum/phonegap-plugin-loading-spinner#27]
Cordova v. 5.1.1
Android Platform v. 4.0.2
When plugin is installed, builds fail with this message:
Missing one of the key attributes 'action#name,category#name' on element intent-filter at AndroidManifest.xml:15:13

Removing this plugin solves the problem.

**Comment by mauriziopinotti** [comment]
This plugin is not compatible with cordova 5. We don't have plans to upgrade for the time being, however we're accepting pull requests to port the plugin to new cordova versions.

**Comment by whyameye** [comment]
Could you please add a note that it is not compatible with Cordova 5 in your readme then? That would be helpful for others so they don't spend time rediscovering what you already know.

**Comment by mauriziopinotti** [comment]
I can make it more visible, but the first line of the README says "PhoneGap 3 plugin to show a loading spinner with optional dark overlay".

**Comment by whyameye** [comment]
Ok I guess from your point of view then there's an understanding in the community that "PhoneGap 3 blah-blah" means "PhoneGap 3 and no other versions." I didn't have that understanding but now I will watch for it.

If it were me I'd put a note right at the top that says "Note: This plugin works for PhoneGap and Cordova version 3 only. It does not work with later versions of PhoneGap or Cordova."

And in an ideal world with limitless time. ;-) I also might also consider adding a test in the plugin to detect if the version of PG or Cordova is wrong and notify the user. The error I got was a bit confusing and didn't tell me which plugin was the problem.

**Comment by whyameye** [comment]
Oops. You already did all this. :-) Deleting both these comments now.
